timestamp,category,user_id,function,line_number,flag,message,exception
2024-06-13 14:35:57,ERROR,demo13,create_or_pass_folder,202,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\app.py"", line 195, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:e73270a0-401e-0035-1370-bddb53000000
Time:2024-06-13T09:05:57.2183037Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:e73270a0-401e-0035-1370-bddb53000000
Time:2024-06-13T09:05:57.2183037Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error>"
2024-06-13 14:35:57,ERROR,demo13,create_or_pass_folder,211,0,"Function create_or_pass_folder Error creating folder'demo13': Value for one of the query parameters specified in the request URI is invalid.
RequestId:e73270a0-401e-0035-1370-bddb53000000
Time:2024-06-13T09:05:57.2183037Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:e73270a0-401e-0035-1370-bddb53000000
Time:2024-06-13T09:05:57.2183037Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'demo13': Value for one of the query parameters specified in the request URI is invalid.
RequestId:e73270a0-401e-0035-1370-bddb53000000
Time:2024-06-13T09:05:57.2183037Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:e73270a0-401e-0035-1370-bddb53000000
Time:2024-06-13T09:05:57.2183037Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\app.py"", line 195, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:e73270a0-401e-0035-1370-bddb53000000
Time:2024-06-13T09:05:57.2183037Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:e73270a0-401e-0035-1370-bddb53000000
Time:2024-06-13T09:05:57.2183037Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error>"
2024-06-13 14:35:57,INFO,demo13,home,1411,1,User demo13 logged in successfully,
2024-06-13 14:35:57,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:36:02,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:36:04,INFO,demo13,get_data_source,2159,1,table_update route successfully send data,
2024-06-13 14:36:33,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:36:35,INFO,demo13,get_data_source,2159,1,table_update route successfully send data,
2024-06-13 14:36:40,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:36:43,INFO,demo13,get_data_source,2159,1,table_update route successfully send data,
2024-06-13 14:36:49,INFO,demo13,upload_to_blob,260,1,Function upload_to_blob successfully created blob_client.url,
2024-06-13 14:36:49,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:36:49,INFO,demo13,popup_form,1543,1,Data Uploaded Successfully,
2024-06-13 14:36:51,INFO,demo13,get_data_source,2159,1,table_update route successfully send data,
2024-06-13 14:36:58,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:37:01,INFO,demo13,get_data_source,2159,1,table_update route successfully send data,
2024-06-13 14:37:15,INFO,demo13,upload_to_blob,260,1,Function upload_to_blob successfully created blob_client.url,
2024-06-13 14:37:15,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:37:15,INFO,demo13,popup_form,1543,1,Data Uploaded Successfully,
2024-06-13 14:37:17,INFO,demo13,get_data_source,2159,1,table_update route successfully send data,
2024-06-13 14:37:21,INFO,demo13,Cogni_button,1726,1,CogniLink load button pressed,
2024-06-13 14:37:31,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:37:46,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:37:48,INFO,demo13,update_when_file_delete,602,1,Function update_when_file_delete Data Loaded Successfully,
2024-06-13 14:37:48,INFO,demo13,Cogni_button,1738,1,Load Data Function executed in 26.891074895858765 seconds,
2024-06-13 14:37:51,INFO,demo13,get_data_source,2159,1,table_update route successfully send data,
2024-06-13 14:38:19,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:38:22,INFO,demo13,get_data_source,2159,1,table_update route successfully send data,
2024-06-13 14:40:06,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:40:14,INFO,demo13,get_data_source,2159,1,table_update route successfully send data,
2024-06-13 14:41:09,INFO,demo13,get_data_source,2159,1,table_update route successfully send data,
2024-06-13 14:44:31,ERROR,demo13,create_or_pass_folder,202,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\app.py"", line 195, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:e7357436-401e-0035-6d72-bddb53000000
Time:2024-06-13T09:14:31.2384684Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:e7357436-401e-0035-6d72-bddb53000000
Time:2024-06-13T09:14:31.2384684Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error>"
2024-06-13 14:44:31,ERROR,demo13,create_or_pass_folder,211,0,"Function create_or_pass_folder Error creating folder'demo13': Value for one of the query parameters specified in the request URI is invalid.
RequestId:e7357436-401e-0035-6d72-bddb53000000
Time:2024-06-13T09:14:31.2384684Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:e7357436-401e-0035-6d72-bddb53000000
Time:2024-06-13T09:14:31.2384684Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'demo13': Value for one of the query parameters specified in the request URI is invalid.
RequestId:e7357436-401e-0035-6d72-bddb53000000
Time:2024-06-13T09:14:31.2384684Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:e7357436-401e-0035-6d72-bddb53000000
Time:2024-06-13T09:14:31.2384684Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\app.py"", line 195, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\Main_CogniLink_App\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:e7357436-401e-0035-6d72-bddb53000000
Time:2024-06-13T09:14:31.2384684Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:demo13
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:e7357436-401e-0035-6d72-bddb53000000
Time:2024-06-13T09:14:31.2384684Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>demo13</QueryParameterValue></Error>"
2024-06-13 14:44:31,INFO,demo13,home,1411,1,User demo13 logged in successfully,
2024-06-13 14:44:31,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:44:35,INFO,demo13,update_bar_chart_from_blob,323,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-06-13 14:44:43,INFO,demo13,get_data_source,2159,1,table_update route successfully send data,
