timestamp,category,user_id,function,line_number,flag,message,exception
2024-07-03 13:18:58,ERROR,asif24,create_or_pass_folder,226,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 219, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:b7b718f4-901e-0015-281d-cdb79f000000
Time:2024-07-03T07:48:57.8437102Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b7b718f4-901e-0015-281d-cdb79f000000
Time:2024-07-03T07:48:57.8437102Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-03 13:18:58,ERROR,asif24,create_or_pass_folder,235,0,"Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:b7b718f4-901e-0015-281d-cdb79f000000
Time:2024-07-03T07:48:57.8437102Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b7b718f4-901e-0015-281d-cdb79f000000
Time:2024-07-03T07:48:57.8437102Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'asif24': Value for one of the query parameters specified in the request URI is invalid.
RequestId:b7b718f4-901e-0015-281d-cdb79f000000
Time:2024-07-03T07:48:57.8437102Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b7b718f4-901e-0015-281d-cdb79f000000
Time:2024-07-03T07:48:57.8437102Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 219, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:b7b718f4-901e-0015-281d-cdb79f000000
Time:2024-07-03T07:48:57.8437102Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:asif24
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:b7b718f4-901e-0015-281d-cdb79f000000
Time:2024-07-03T07:48:57.8437102Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>asif24</QueryParameterValue></Error>"
2024-07-03 13:18:58,INFO,asif24,home,1704,1,User asif24 logged in successfully,
2024-07-03 13:18:58,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:19:02,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:19:05,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:19:05,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
2024-07-03 13:19:16,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:19:16,INFO,asif24,popup_form,2155,1,Data Uploaded Successfully,
2024-07-03 13:19:18,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:19:18,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
2024-07-03 13:19:34,INFO,asif24,Cogni_button,2338,1,CogniLink load button pressed,
2024-07-03 13:19:35,ERROR,asif24,update_when_file_delete,855,0,Function update_when_file_delete error,"Function update_when_file_delete error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\app.py"", line 624, in update_when_file_delete
    chunks = loader.load_and_split()
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\document_loaders\base.py"", line 63, in load_and_split
    docs = self.load()
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_core\document_loaders\base.py"", line 29, in load
    return list(self.lazy_load())
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_community\document_loaders\web_base.py"", line 249, in lazy_load
    soup = self._scrape(path, bs_kwargs=self.bs_kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\langchain_community\document_loaders\web_base.py"", line 228, in _scrape
    html_doc = self.session.get(url, **self.requests_kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\requests\sessions.py"", line 602, in get
    return self.request(""GET"", url, **kwargs)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\requests\sessions.py"", line 575, in request
    prep = self.prepare_request(req)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\requests\sessions.py"", line 486, in prepare_request
    p.prepare(
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\requests\models.py"", line 368, in prepare
    self.prepare_url(url, params)
  File ""C:\Users\Asif\Desktop\letest_dev_cpde\Test_Load\venv\lib\site-packages\requests\models.py"", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'website': No scheme supplied. Perhaps you meant https://website?"
2024-07-03 13:19:35,INFO,asif24,Cogni_button,2350,1,Load Data Function executed in 1.3701355457305908 seconds,
2024-07-03 13:19:38,INFO,asif24,update_bar_chart_from_blob,413,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-03 13:19:38,INFO,asif24,get_data_source,3131,1,table_update route successfully sent data,
