timestamp,category,user_id,function,line_number,flag,message,exception
2024-07-05 15:03:26,ERROR,san123,create_or_pass_folder,233,0,Function create_or_pass_folder error,"Function create_or_pass_folder error
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\Dev-Cogni-Code\Test_Load\app.py"", line 226, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\Dev-Cogni-Code\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\Dev-Cogni-Code\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\Dev-Cogni-Code\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\Dev-Cogni-Code\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:fcc776d8-901e-0051-54be-ce6bf3000000
Time:2024-07-05T09:33:26.7418319Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:san123
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:fcc776d8-901e-0051-54be-ce6bf3000000
Time:2024-07-05T09:33:26.7418319Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>san123</QueryParameterValue></Error>"
2024-07-05 15:03:27,ERROR,san123,create_or_pass_folder,242,0,"Function create_or_pass_folder Error creating folder'san123': Value for one of the query parameters specified in the request URI is invalid.
RequestId:fcc776d8-901e-0051-54be-ce6bf3000000
Time:2024-07-05T09:33:26.7418319Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:san123
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:fcc776d8-901e-0051-54be-ce6bf3000000
Time:2024-07-05T09:33:26.7418319Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>san123</QueryParameterValue></Error> ","Function create_or_pass_folder Error creating folder'san123': Value for one of the query parameters specified in the request URI is invalid.
RequestId:fcc776d8-901e-0051-54be-ce6bf3000000
Time:2024-07-05T09:33:26.7418319Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:san123
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:fcc776d8-901e-0051-54be-ce6bf3000000
Time:2024-07-05T09:33:26.7418319Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>san123</QueryParameterValue></Error> 
Traceback (most recent call last):
  File ""C:\Users\Asif\Desktop\Dev-Cogni-Code\Test_Load\app.py"", line 226, in create_or_pass_folder
    container_client.get_blob_client(container_name, user_folder).upload_blob("""")
  File ""C:\Users\Asif\Desktop\Dev-Cogni-Code\Test_Load\venv\lib\site-packages\azure\core\tracing\decorator.py"", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File ""C:\Users\Asif\Desktop\Dev-Cogni-Code\Test_Load\venv\lib\site-packages\azure\storage\blob\_blob_client.py"", line 765, in upload_blob
    return upload_block_blob(**options)
  File ""C:\Users\Asif\Desktop\Dev-Cogni-Code\Test_Load\venv\lib\site-packages\azure\storage\blob\_upload_helpers.py"", line 195, in upload_block_blob
    process_storage_error(error)
  File ""C:\Users\Asif\Desktop\Dev-Cogni-Code\Test_Load\venv\lib\site-packages\azure\storage\blob\_shared\response_handlers.py"", line 184, in process_storage_error
    exec(""raise error from None"")   # pylint: disable=exec-used # nosec
  File ""<string>"", line 1, in <module>
azure.core.exceptions.HttpResponseError: Value for one of the query parameters specified in the request URI is invalid.
RequestId:fcc776d8-901e-0051-54be-ce6bf3000000
Time:2024-07-05T09:33:26.7418319Z
ErrorCode:InvalidQueryParameterValue
queryparametername:snapshot
queryparametervalue:san123
Content: <?xml version=""1.0"" encoding=""utf-8""?>
<Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:fcc776d8-901e-0051-54be-ce6bf3000000
Time:2024-07-05T09:33:26.7418319Z</Message><QueryParameterName>snapshot</QueryParameterName><QueryParameterValue>san123</QueryParameterValue></Error>"
2024-07-05 15:03:27,INFO,san123,home,1752,1,User san123 logged in successfully,
2024-07-05 15:03:27,INFO,san123,update_bar_chart_from_blob,420,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-05 15:03:30,INFO,san123,update_bar_chart_from_blob,420,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-05 15:03:37,INFO,san123,update_bar_chart_from_blob,420,1,Function update_bar_chart_from_blob successfully Return blob_list,
2024-07-05 15:03:37,INFO,san123,get_data_source,3075,1,table_update route successfully sent data,
